import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f0f1f2",
        "surface-dim": "#d9dadb",
        "on-surface": "#191c1d",
        "surface-container-high": "#e7e8e9",
        "surface-tint": "#4d44e3",
        "on-tertiary-container": "#ffd2be",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdbcc",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#464555",
        "on-secondary-fixed": "#140f54",
        primary: "#3525cd",
        "surface-bright": "#f8f9fa",
        "on-tertiary-fixed": "#351000",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-low": "#f3f4f5",
        outline: "#777587",
        surface: "#f8f9fa",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-container": "#edeeef",
        "outline-variant": "#c7c4d8",
        "on-primary-fixed": "#0f0069",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#c3c0ff",
        "inverse-primary": "#c3c0ff",
        "on-primary-container": "#dad7ff",
        error: "#ba1a1a",
        "secondary-container": "#b6b4ff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "surface-variant": "#e1e3e4",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb695",
        secondary: "#58579b",
        "primary-fixed-dim": "#c3c0ff",
        "primary-container": "#4f46e5",
        "surface-container-highest": "#e1e3e4",
        "secondary-fixed": "#e2dfff",
        "on-secondary-container": "#454386",
        "on-secondary": "#ffffff",
        "on-background": "#191c1d",
        "on-secondary-fixed-variant": "#413f82",
        tertiary: "#7e3000",
        background: "#f8f9fa",
        "tertiary-container": "#a44100",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "4px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        "2xl": "48px",
      },
      boxShadow: {
        ambient: "0 20px 40px rgba(25, 28, 29, 0.06)",
      },
      backdropBlur: {
        glass: "24px",
      },
      backgroundImage: {
        ctaGradient: "linear-gradient(135deg, #3525cd 0%, #4f46e5 100%)",
      },
      fontFamily: {
        headline: ["var(--font-inter)", "Inter", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
