CREATE TABLE IF NOT EXISTS inventory (
  product_id VARCHAR(64) PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,
  sku VARCHAR(64) NOT NULL UNIQUE,
  on_hand INTEGER NOT NULL,
  reserved INTEGER NOT NULL DEFAULT 0
);
